### PR TITLE
Redesign - using schemas

### LINKED ISSUE #2: Release first version

### LINKED ISSUE #17: Design an error handling system for volga

### LINKED ISSUE #18: Design decisions on how to deal with serialization and deserialization for Python primitives
We talked about defining our own types, like having wrapper classes, current implementation uses the [if block](https://github.com/yefrig/volga/blob/bdacd125ed2f76db19edf850a0112bd6388576b8/src/format.py#L77-L93)

### LINKED ISSUE #33: Add User model to readme, type should not be schema

### PR DESCRIPTION
**Pull request by eozmen410**
Relates to our discussion on #18 
Using wrapper classes for primitives

### CODE REVIEW

**Comment by yefrig** [comment]
We still need to fix protocols and types. We also need to add static methods to Field classes so that the user does not have to implement these

**Comment by yefrig** [comment]
Finally decided on __deserialize__ and Format protocols. Types are now fixed for most functions. Using TypeVar with the SupportsDeser protocol as the upper bound.

**Comment by yefrig** [comment]
TODO:

- [ ] Make every `Field` class subclass python primitives. The idea is that our field types will be interchangeable with python primitives but can also be deserialized by any data format (they are wrappers)
- [ ] Figure out how to autogenerate `__deserialize__` and `__from_*__` methods for simple classes that just use our field `Field`
- [ ] Create tests for `JSON` parser/deserializer
- [ ] Add classes for all 6 supported fields (`int`, `float`, `str`, `bool`, `none`, `dict`) and subclass their respective primitive
- [ ] Add non-abstract methods that raise `NotImplementedError` errors to base classes so that subclasses don't have that burden for methods that they don't implement
- [ ] Create classes for Errors and pretty printing relates to #17 
- [ ] Update README w/ new redesign

**Review by eozmen410 — COMMENTED** [review]
LGTM!

**Pull request merged**
